version: '3'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [32789]
  redis:
    image: redis:5-alpine
    ports: [6379]