washimimizuku_api:
    resource: "@WashimimizukuAPIBundle/Resources/config/routing.yml"
    prefix:   /

users:
    type:     rest
    resource: Washimimizuku\Bundle\APIBundle\Controller\UsersController
